scriber/models/book.py
from scriber.extensions import db

class Book(db.Model):
    isbn = db.Column(db.Integer, primary_key=True, unique=True, nullable=False)
    title = db.Column(db.String(50), nullable=False)
    author = db.Column(db.String(50), nullable=False)
    description = db.Column(db.String(300))
    cover = db.Column(db.String(50))
    reviews = db.relationship('Review', backref='book', lazy=True)

    def __repr__(self):
        return f'<Book "{self.title}">'

scriber/models/review.py
from scriber.extensions import db

class Review(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    book_id = db.Column(db.Integer, db.ForeignKey('book.isbn'), nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    title = db.Column(db.String(30), nullable=False)
    review_text = db.Column(db.String(300), nullable=False)
    created = db.Column(db.DateTime)

scriber/models/user.py
from scriber.extensions import db

class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(15), nullable=False, unique=True)
    email = db.Column(db.String(30), nullable=False)
    password_hash = db.Column(db.String(20), nullable=False)
    is_admin = db.Column(db.Boolean)

scriber/forms/user.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField
from wtforms.validators import DataRequired, Length, Email, EqualTo

class LoginForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired(), Length(min=3, max=20)])
    password = PasswordField('Password', validators=[DataRequired(), Length(min=8, max=30)])
    email  = StringField('Email', validators=[DataRequired(), Email(message="Please enter a valid email address")])
    remember = BooleanField('Remember Me')
    submit = SubmitField('Login')

class RegisterForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired(), Length(min=3, max=20)])
    email  = StringField('Email', validators=[DataRequired(), Email(message="Please enter a valid email address")])
    password = PasswordField('Password', validators=[DataRequired(), Length(min=3, max=30)])
    confirm_password = PasswordField('Confirm Password', validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField('Sign Up')

scriber/__init__.py
import os
from flask import Flask
from dotenv import load_dotenv
from flask import Blueprint
from scriber.extensions import db

load_dotenv()

def create_app(test_config=None):
    from . import api, site, auth
    
    app = Flask(__name__, instance_relative_config=True)
    app.config.from_envvar('APP_CONFIG')
    if test_config is None:
        # load the instance config, if it exists, when not testing
        app.config.from_pyfile('config.py', silent=True)
    else:
        # load the test config if passed in
        app.config.from_mapping(test_config)

    # ensure the instance folder exists
    try:
        os.makedirs(app.instance_path)
    except OSError:
        pass

    db.init_app(app)
    
    from scriber.auth import bp as auth_bp
    app.register_blueprint(auth_bp)

    from scriber.site import bp as site_bp
    app.register_blueprint(site_bp)
    
    @app.route('/hello')
    def hello():
        return 'Hello there'
    
    return app

scriber/site/__init__.py
from flask import Blueprint


bp = Blueprint('site', __name__)

from scriber.site import routes

scriber/site/routes.py
from scriber.site import bp
from flask import render_template

@bp.route('/')
def index():
    return render_template('index.html')

scriber/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/b28eec4103.js" crossorigin="anonymous"></script>
    <title>{% block title %} {% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-light bg-light">
        <div class="container-fluid">
            <i class="fa-solid fa-book"></i>
            <span class="navbar-brand">Scriber</span>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>          
            <div class="collapse navbar-collapse", id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{{url_for('site.index')}}">Home</a>
                    </li>
                    {% if g.user %}
                    <li class="nav-item">
                        <a class="nav-link" href="#">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{url_for('auth.register')}}">Sign Up</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{url_for('auth.login')}}">Login</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    {% block content %} {% endblock %}
</body>
</html>

scriber/templates/index.html
{% extends 'base.html' %}
{% block title %}
Scriber
{% endblock %}
{% block content %}
    <h1>This is the index page</h1>
{% endblock %}

scriber/templates/login.html
{% extends 'base.html' %}
{% block title %}
Login
{% endblock %}
{% block content %}
    <div>
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}
                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span> {{ error }} </span>
                            {% endfor %}
                        </div>
                    {% endif %}
                    {{ form.username(class="form-control form-control-lg") }}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span> {{ error }} </span>
                            {% endfor %}
                        </div>
                    {% endif %}
                    {{ form.email(class="form-control from-control-lg") }}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span> {{ error }} </span>
                            {% endfor %}
                        </div>
                    {% endif %}
                    {{ form.password(class="form-control from-control-lg") }}
                </div>
            </fieldset>
            <div>
                {{ form.submit(class="btn btn-outline-success") }}
            </div>
        </form>
    </div>
{% endblock %}